"""add_workout_plans_and_traceability

Revision ID: 5ea4d898b3f0
Revises: d8cd5dba63a7
Create Date: 2026-03-08 04:04:38.630022+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea4d898b3f0'
down_revision = 'd8cd5dba63a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'QUEUED', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='planstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_id'), 'workout_plans', ['id'], unique=False)
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_table('plan_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_weeks_id'), 'plan_weeks', ['id'], unique=False)
    op.create_index(op.f('ix_plan_weeks_plan_id'), 'plan_weeks', ['plan_id'], unique=False)
    op.create_table('plan_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_id'], ['plan_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'day_of_week', name='uq_plan_day_week_dow')
    )
    op.create_index(op.f('ix_plan_days_id'), 'plan_days', ['id'], unique=False)
    op.create_index(op.f('ix_plan_days_week_id'), 'plan_days', ['week_id'], unique=False)
    op.add_column('workout_sessions', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('workout_sessions', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workout_sessions_plan_id'), 'workout_sessions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_template_id'), 'workout_sessions', ['template_id'], unique=False)
    op.create_foreign_key(None, 'workout_sessions', 'workout_plans', ['plan_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workout_sessions', 'workout_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_sessions', type_='foreignkey')
    op.drop_constraint(None, 'workout_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_workout_sessions_template_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_plan_id'), table_name='workout_sessions')
    op.drop_column('workout_sessions', 'plan_id')
    op.drop_column('workout_sessions', 'template_id')
    op.drop_index(op.f('ix_plan_days_week_id'), table_name='plan_days')
    op.drop_index(op.f('ix_plan_days_id'), table_name='plan_days')
    op.drop_table('plan_days')
    op.drop_index(op.f('ix_plan_weeks_plan_id'), table_name='plan_weeks')
    op.drop_index(op.f('ix_plan_weeks_id'), table_name='plan_weeks')
    op.drop_table('plan_weeks')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_index(op.f('ix_workout_plans_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    # ### end Alembic commands ###
