"""add_workout_templates_and_template_exercises

Revision ID: d8cd5dba63a7
Revises: 082c084afd2f
Create Date: 2025-12-22 00:12:45.291977+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cd5dba63a7'
down_revision = '082c084afd2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_templates_user_id'), 'workout_templates', ['user_id'], unique=False)
    op.create_table('template_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_exercises_template_id'), 'template_exercises', ['template_id'], unique=False)
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('log_exercises', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('log_exercises', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_log_sets_composite'), table_name='log_sets')
    op.drop_index(op.f('idx_log_sets_log_exercise_id'), table_name='log_sets')
    op.drop_constraint(op.f('uq_log_sets_exercise_set'), 'log_sets', type_='unique')
    op.create_index(op.f('ix_log_sets_log_exercise_id'), 'log_sets', ['log_exercise_id'], unique=False)
    op.alter_column('workout_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_sessions', 'workout_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sessions', 'workout_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('workout_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_log_sets_log_exercise_id'), table_name='log_sets')
    op.create_unique_constraint(op.f('uq_log_sets_exercise_set'), 'log_sets', ['log_exercise_id', 'set_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_log_sets_log_exercise_id'), 'log_sets', ['log_exercise_id'], unique=False)
    op.create_index(op.f('idx_log_sets_composite'), 'log_sets', ['log_exercise_id', 'set_number'], unique=False)
    op.alter_column('log_exercises', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('log_exercises', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_template_exercises_template_id'), table_name='template_exercises')
    op.drop_table('template_exercises')
    op.drop_index(op.f('ix_workout_templates_user_id'), table_name='workout_templates')
    op.drop_table('workout_templates')
    # ### end Alembic commands ###
