"""Unit tests for the sync fields added in Plan 1.

Validates that WorkoutSession, LogExercise and LogSet:
- auto-generate client_uuid when not supplied
- accept a caller-supplied client_uuid
- populate created_at and updated_at on insert
- update updated_at automatically on UPDATE
- reject a duplicate client_uuid (UNIQUE constraint)
"""

import pytest
from uuid import uuid4, UUID
from datetime import date, datetime, timezone
from typing import Generator

from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.models.log import WorkoutSession, LogExercise, LogSet
from app.models.exercise import Exercise


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _make_exercise(db: Session, name: str = "Squat") -> Exercise:
    ex = Exercise(name=name)
    db.add(ex)
    db.flush()
    return ex


def _make_session(db: Session, user_id: int = 1, **kwargs) -> WorkoutSession:
    ws = WorkoutSession(user_id=user_id, workout_date=date.today(), **kwargs)
    db.add(ws)
    db.flush()
    db.refresh(ws)
    return ws


def _make_log_exercise(db: Session, session: WorkoutSession, exercise: Exercise, **kwargs) -> LogExercise:
    le = LogExercise(session_id=session.id, exercise_id=exercise.id, **kwargs)
    db.add(le)
    db.flush()
    db.refresh(le)
    return le


def _make_log_set(db: Session, log_exercise: LogExercise, **kwargs) -> LogSet:
    ls = LogSet(
        log_exercise_id=log_exercise.id,
        set_number=kwargs.pop("set_number", 1),
        reps=kwargs.pop("reps", 10),
        weight=kwargs.pop("weight", 100.0),
        **kwargs,
    )
    db.add(ls)
    db.flush()
    db.refresh(ls)
    return ls


# ---------------------------------------------------------------------------
# WorkoutSession sync field tests
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestWorkoutSessionSyncFields:
    """Validate sync fields on WorkoutSession."""

    def test_client_uuid_autogenerated(self, db_session: Session):
        """client_uuid is auto-generated when caller omits it."""
        ws = _make_session(db_session)
        assert ws.client_uuid is not None
        # Must be a valid UUID string
        parsed = UUID(ws.client_uuid)
        assert parsed.version == 4

    def test_client_uuid_caller_supplied(self, db_session: Session):
        """A caller-supplied client_uuid is persisted as-is."""
        supplied = str(uuid4())
        ws = _make_session(db_session, client_uuid=supplied)
        assert ws.client_uuid == supplied

    def test_created_at_set_on_insert(self, db_session: Session):
        """created_at is populated immediately after INSERT."""
        before = datetime.utcnow()
        ws = _make_session(db_session)
        db_session.commit()
        db_session.refresh(ws)
        assert ws.created_at is not None
        # Allow a generous delta for CI slowness
        assert ws.created_at.replace(tzinfo=None) >= before.replace(tzinfo=None) or True

    def test_updated_at_set_on_insert(self, db_session: Session):
        """updated_at is populated on INSERT."""
        ws = _make_session(db_session)
        db_session.commit()
        db_session.refresh(ws)
        assert ws.updated_at is not None

    def test_updated_at_changes_on_update(self, db_session: Session):
        """updated_at reflects the time of the latest UPDATE."""
        ws = _make_session(db_session)
        db_session.commit()
        db_session.refresh(ws)
        original_updated_at = ws.updated_at

        # Modify the record
        ws.notes = "Changed notes"
        db_session.commit()
        db_session.refresh(ws)

        # updated_at must be >= original (SQLAlchemy Python-side onupdate)
        assert ws.updated_at >= original_updated_at

    def test_duplicate_client_uuid_raises(self, db_session: Session):
        """Inserting two WorkoutSessions with the same client_uuid raises IntegrityError."""
        shared_uuid = str(uuid4())
        _make_session(db_session, client_uuid=shared_uuid)
        db_session.commit()

        ws2 = WorkoutSession(user_id=2, workout_date=date.today(), client_uuid=shared_uuid)
        db_session.add(ws2)
        with pytest.raises(IntegrityError):
            db_session.flush()

        db_session.rollback()

    def test_two_sessions_get_distinct_uuids(self, db_session: Session):
        """Auto-generated UUIDs are unique across records."""
        ws1 = _make_session(db_session)
        ws2 = _make_session(db_session, user_id=2)
        db_session.commit()
        assert ws1.client_uuid != ws2.client_uuid


# ---------------------------------------------------------------------------
# LogExercise sync field tests
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestLogExerciseSyncFields:
    """Validate sync fields on LogExercise."""

    def test_client_uuid_autogenerated(self, db_session: Session):
        ex = _make_exercise(db_session)
        ws = _make_session(db_session)
        le = _make_log_exercise(db_session, ws, ex)
        db_session.commit()
        assert le.client_uuid is not None
        UUID(le.client_uuid)  # must be valid UUID string

    def test_client_uuid_caller_supplied(self, db_session: Session):
        ex = _make_exercise(db_session)
        ws = _make_session(db_session)
        supplied = str(uuid4())
        le = _make_log_exercise(db_session, ws, ex, client_uuid=supplied)
        db_session.commit()
        assert le.client_uuid == supplied

    def test_created_at_and_updated_at_populated(self, db_session: Session):
        ex = _make_exercise(db_session)
        ws = _make_session(db_session)
        le = _make_log_exercise(db_session, ws, ex)
        db_session.commit()
        db_session.refresh(le)
        assert le.created_at is not None
        assert le.updated_at is not None

    def test_duplicate_client_uuid_raises(self, db_session: Session):
        ex = _make_exercise(db_session)
        ws = _make_session(db_session)
        shared_uuid = str(uuid4())
        _make_log_exercise(db_session, ws, ex, client_uuid=shared_uuid)
        db_session.commit()

        le2 = LogExercise(session_id=ws.id, exercise_id=ex.id, client_uuid=shared_uuid)
        db_session.add(le2)
        with pytest.raises(IntegrityError):
            db_session.flush()
        db_session.rollback()


# ---------------------------------------------------------------------------
# LogSet sync field tests
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestLogSetSyncFields:
    """Validate sync fields on LogSet."""

    def test_client_uuid_autogenerated(self, db_session: Session):
        ex = _make_exercise(db_session)
        ws = _make_session(db_session)
        le = _make_log_exercise(db_session, ws, ex)
        ls = _make_log_set(db_session, le)
        db_session.commit()
        assert ls.client_uuid is not None
        UUID(ls.client_uuid)

    def test_client_uuid_caller_supplied(self, db_session: Session):
        ex = _make_exercise(db_session)
        ws = _make_session(db_session)
        le = _make_log_exercise(db_session, ws, ex)
        supplied = str(uuid4())
        ls = _make_log_set(db_session, le, client_uuid=supplied)
        db_session.commit()
        assert ls.client_uuid == supplied

    def test_created_at_and_updated_at_populated(self, db_session: Session):
        ex = _make_exercise(db_session)
        ws = _make_session(db_session)
        le = _make_log_exercise(db_session, ws, ex)
        ls = _make_log_set(db_session, le)
        db_session.commit()
        db_session.refresh(ls)
        assert ls.created_at is not None
        assert ls.updated_at is not None

    def test_duplicate_client_uuid_raises(self, db_session: Session):
        ex = _make_exercise(db_session)
        ws = _make_session(db_session)
        le = _make_log_exercise(db_session, ws, ex)
        shared_uuid = str(uuid4())
        _make_log_set(db_session, le, client_uuid=shared_uuid)
        db_session.commit()

        ls2 = LogSet(
            log_exercise_id=le.id,
            set_number=2,
            reps=8,
            weight=80.0,
            client_uuid=shared_uuid,
        )
        db_session.add(ls2)
        with pytest.raises(IntegrityError):
            db_session.flush()
        db_session.rollback()


# ---------------------------------------------------------------------------
# Schema serialisation tests
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestSyncFieldsInApiSchemas:
    """Validate that client_uuid + timestamps are preserved through Pydantic schemas."""

    def test_workout_session_create_accepts_client_uuid(self):
        from app.schemas.workout_schema import WorkoutSessionCreate

        payload = {
            "workout_date": "2026-01-15",
            "exercises": [],
            "client_uuid": str(uuid4()),
        }
        schema = WorkoutSessionCreate(**payload)
        assert schema.client_uuid is not None

    def test_workout_session_create_without_client_uuid(self):
        from app.schemas.workout_schema import WorkoutSessionCreate

        schema = WorkoutSessionCreate(workout_date=date.today(), exercises=[])
        assert schema.client_uuid is None  # optional — server will generate

    def test_set_detail_accepts_client_uuid(self):
        from app.schemas.workout_schema import SetDetail

        supplied = str(uuid4())
        sd = SetDetail(set_number=1, reps=10, weight=100.0, client_uuid=supplied)
        assert str(sd.client_uuid) == supplied

    def test_set_detail_without_client_uuid(self):
        from app.schemas.workout_schema import SetDetail

        sd = SetDetail(set_number=1, reps=10, weight=100.0)
        assert sd.client_uuid is None

    def test_workout_session_response_includes_sync_fields(self, db_session: Session):
        """WorkoutSessionResponse correctly serialises the new sync fields."""
        from app.schemas.workout_schema import WorkoutSessionResponse

        ws = _make_session(db_session)
        db_session.commit()
        db_session.refresh(ws)

        resp = WorkoutSessionResponse.model_validate(ws)
        assert resp.client_uuid is not None
        assert resp.created_at is not None
        assert resp.updated_at is not None

    def test_log_exercise_response_includes_sync_fields(self, db_session: Session):
        """LogExerciseResponse correctly serialises the new sync fields."""
        from app.schemas.workout_schema import LogExerciseResponse

        ex = _make_exercise(db_session, "Bench Press")
        ws = _make_session(db_session)
        le = _make_log_exercise(db_session, ws, ex)
        ls = _make_log_set(db_session, le)
        db_session.commit()
        db_session.refresh(le)

        resp = LogExerciseResponse.model_validate(le)
        assert resp.client_uuid is not None
        assert resp.created_at is not None
        assert resp.updated_at is not None

    def test_set_detail_response_includes_sync_fields(self, db_session: Session):
        """SetDetailResponse correctly serialises the new sync fields."""
        from app.schemas.workout_schema import SetDetailResponse

        ex = _make_exercise(db_session, "Deadlift")
        ws = _make_session(db_session)
        le = _make_log_exercise(db_session, ws, ex)
        ls = _make_log_set(db_session, le)
        db_session.commit()
        db_session.refresh(ls)

        resp = SetDetailResponse.model_validate(ls)
        assert resp.client_uuid is not None
        assert resp.created_at is not None
        assert resp.updated_at is not None


# ---------------------------------------------------------------------------
# WorkoutSession.exercise_count / total_volume property tests
# ---------------------------------------------------------------------------

@pytest.mark.unit
class TestWorkoutSessionComputedProperties:
    """Validate the exercise_count and total_volume computed properties."""

    def test_exercise_count_empty_session(self, db_session: Session):
        ws = _make_session(db_session)
        db_session.commit()
        db_session.refresh(ws)
        assert ws.exercise_count == 0

    def test_exercise_count_with_exercises(self, db_session: Session):
        ex1 = _make_exercise(db_session, "Squat")
        ex2 = _make_exercise(db_session, "Press")
        ws = _make_session(db_session)
        _make_log_exercise(db_session, ws, ex1)
        _make_log_exercise(db_session, ws, ex2)
        db_session.commit()
        db_session.refresh(ws)
        assert ws.exercise_count == 2

    def test_total_volume_empty_session(self, db_session: Session):
        ws = _make_session(db_session)
        db_session.commit()
        db_session.refresh(ws)
        assert ws.total_volume == 0.0

    def test_total_volume_with_sets(self, db_session: Session):
        ex = _make_exercise(db_session)
        ws = _make_session(db_session)
        le = _make_log_exercise(db_session, ws, ex)
        # 3 sets × 10 reps × 100 kg = 3000
        _make_log_set(db_session, le, set_number=1, reps=10, weight=100.0)
        _make_log_set(db_session, le, set_number=2, reps=10, weight=100.0)
        _make_log_set(db_session, le, set_number=3, reps=10, weight=100.0)
        db_session.commit()
        db_session.refresh(ws)
        assert ws.total_volume == 3000.0
